include(":core")
include(":samples:iceandfire:foundation")
include(":samples:iceandfire:foundation:mock")
include(":samples:iceandfire:app")
include(":samples:iceandfire:app:android")
include(":samples:iceandfire:app:fake")
include(":samples:iceandfire:app:web")
